### ISSUE TITLE
Парсер на Go

### ISSUE THREAD

**Issue by LazarenkoA** [tsukanov-as/bslinter#2]
> Почти сразу был переписан на Lua и **Go** в черновом варианте для оценки. В сообществе разработчиков оказался не востребованным.

у тебя в репах не нашел проекта по го, можешь поделиться?

**Comment by tsukanov-as** [comment]
https://github.com/tsukanov-as/radar
Только учти - там лицензия не свободная.
Причина этому простая. Если кто-то хочет помочь, то пусть лучше тут поможет, а не конкурирует со мной моим же творением )
